use telemetryV1;

CREATE EXTERNAL TABLE game_telemetry(key string,
        ab_groups string,
        abtestgroupids string,
        abtestgroups string,
        abtestids string,
        abtestvalues string,
        adjust_first_attributed_tracker_activity_kind bigint,:q
        adjust_latest_attributed_tracker_activity_kind bigint,
        advertiser_id string,
        app_bundle_id string,
        are_coins_doubled boolean,
        binary_version string,
        client_event_time bigint,
        client_event_time_zone bigint,
        client_timezone_offset bigint,
        consecutive_days_played bigint,
        count_of_runs bigint,
        country_code string,
        cumulative_score bigint,
        current_costume string,
        current_energy_level bigint,
        current_lindsey_stirling_tokens bigint,
        device_id string,
        device_model string,
        device_name string,
        enabled_remote_notification_types string,
        evid string,
        first_play_time bigint,
        first_play_time_zone bigint,
        guid string,
        hard_currency_balance bigint,
        is_install boolean,
        is_production_build boolean,
        is_release_build boolean,
        last_iap_time bigint,
        last_login_time bigint,
        last_login_time_zone bigint,
        level bigint,
        lifetime_iap_spend_in_usd_cents bigint,
        speednscale_sdk_version string,
        speednscale_telemetry_version string,
        os_version bigint,
        os_version_full string,
        platform string,
        player_is_logged_in_to_facebook boolean,
        playfab_session_ticket string,
        playfab_title_id string,
        playfab_user_id string,
        popdash_release_version string,
        popdash_telemetry_version string,
        soft_currency_balance bigint,
        time_to_next_energy_refill string,
        title_id bigint,
        ts bigint,
        user_id string,
        recordname string,
        game string
)

        STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
        WITH SERDEPROPERTIES ("hbase.columns.mapping" = ":key,gt:ab_groups,gt:abtestgroupids,gt:abtestgroups,gt:abtestids,gt:abtestvalues,gt:adjust_first_attributed_tracker_activity_kindi#b,gt:adjust_latest_attributed_tracker_activity_kind#b,gt:advertiser_id,gt:app_bundle_id,gt:are_coins_doubled#b,gt:binary_version,gt:client_event_time#b,gt:client_event_time_zone#b,gt:client_timezone_offset#b,gt:consecutive_days_played#b,gt:count_of_runs#b,gt:country_code,gt:cumulative_score#b,gt:current_costume,gt:current_energy_level#b,gt:current_lindsey_stirling_tokens#b,gt:device_id,gt:device_model,gt:device_name,gt:enabled_remote_notification_types,gt:evid,gt:first_play_time#b,gt:first_play_time_zone#b,gt:guid,gt:hard_currency_balance#b,gt:is_install#b,gt:is_production_build#b,gt:is_release_build#b,gt:last_iap_time#b,gt:last_login_time#b,gt:last_login_time_zone#b,gt:level#b,gt:lifetime_iap_spend_in_usd_cents#b,gt:speednscale_sdk_version,gt:speednscale_telemetry_version,gt:os_version#b,gt:os_version_full,gt:platform,gt:player_is_logged_in_to_facebook#b,gt:playfab_session_ticket,gt:playfab_title_id,gt:playfab_user_id,gt:popdash_release_version,gt:popdash_telemetry_version,gt:soft_currency_balance#b,gt:time_to_next_energy_refill,gt:title_id#b,gt:ts#b,gt:user_id,gt:recordname,gt:game"
)
        TBLPROPERTIES("hbase.table.name" = "telemetryV1:game_telemetry");
        